name: ci-sonarcloud
on:
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.0'
      - run: yarn
      - run: yarn test  